# Generated by Django 5.2 on 2025-05-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovedRfpDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_document', models.FileField(upload_to='original_rfps/')),
                ('improved_document', models.FileField(upload_to='improved_rfps/')),
                ('competition_name', models.CharField(max_length=255)),
                ('competition_objectives', models.TextField()),
                ('competition_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
