# Generated by Django 5.2 on 2025-05-17 22:20

import kurrasat.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_improvedrfpdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvedrfpdocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvedrfpdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='improvedrfpdocument',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='improvedrfpdocument',
            name='improved_document',
            field=models.FileField(storage=kurrasat.storage_backends.ImprovedRfpStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='improvedrfpdocument',
            name='original_document',
            field=models.FileField(storage=kurrasat.storage_backends.OriginalRfpStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='rfpdocument',
            name='document_file',
            field=models.FileField(storage=kurrasat.storage_backends.RfpDocumentStorage(), upload_to=''),
        ),
    ]
